### Seismocardiogram smartphone data processing
### WHAT: smartphone is placed on the chest and the resulting acceleration/motion due to the 
#         heartbeat (and breathing and random motions) is measured by the accelerometer and Phyphox app
### INPUT: data from smartphone accelerometer (excel file, body + gravitational acceleration)
### OUTPUT: estimated heartbeat rate and amplitude of chest wall motion

### Pseudocode:
#1. load excel data
#2. cut of starting 3 seconds, apply high pass filter
#   2.1. output signal FFT (used to determine filter cutoff frequencies)
#3. align all heartbeat signals to calculate the average/template signal
#4. plot template + individual signals to asses variablility
#5. integrate acceleration to obtain chest wall displacement due to a heartbeat, output values

### NOTE1: code generated by ChatGPT as a test of its suitability for 
#         aiding data processing for school experiments

# NOTE2: this approach filters and averages out too much of the signal, leading to an underestimate
# of the chest wall motion. If double integration is done on the raw (or only high-pass filtered)
# signal only, the value is much closed to one found in the literature.

# Author: ChatGPT + Selver Pepic
# Date: 06.06.2026.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import butter, filtfilt, find_peaks
from scipy.fft import rfft, rfftfreq
from scipy.integrate import cumulative_trapezoid


# ============================================================
# USER SETTINGS
# ============================================================

EXCEL_FILE = "your_data.xlsx"   # <-- Replace with your file
SHEET_NAME = 0                  # Excel sheet index or name

# Column names in the Excel file
TIME_COLUMN = "Time"
X_COLUMN = "Accel_X"
Y_COLUMN = "Accel_Y"
Z_COLUMN = "Accel_Z"

# Sampling frequency [Hz]
FS = 100.0

# Initial time to remove [s]
CUT_INITIAL_SECONDS = 3.0

# High-pass filter cutoff frequency [Hz]
HP_CUTOFF = 0.5


# ============================================================
# FUNCTIONS
# ============================================================

def highpass_filter(signal, cutoff, fs, order=4):
    nyquist = 0.5 * fs
    normalized_cutoff = cutoff / nyquist

    b, a = butter(order, normalized_cutoff, btype='high')
    filtered = filtfilt(b, a, signal)

    return filtered


def compute_fft(signal, fs):
    n = len(signal)

    yf = np.abs(rfft(signal))
    xf = rfftfreq(n, 1 / fs)

    return xf, yf


def align_and_average_segments(segments):
    reference = segments[0]
    aligned_segments = []

    for seg in segments:
        corr = np.correlate(
            seg - np.mean(seg),
            reference - np.mean(reference),
            mode='full'
        )

        shift = np.argmax(corr) - (len(seg) - 1)

        if shift > 0:
            shifted = np.pad(seg, (shift, 0), mode='constant')[:len(seg)]

        elif shift < 0:
            shifted = np.pad(seg, (0, -shift), mode='constant')[-shift:]

        else:
            shifted = seg.copy()

        aligned_segments.append(shifted)

    aligned_segments = np.array(aligned_segments)

    average_template = np.mean(aligned_segments, axis=0)

    return aligned_segments, average_template


# ============================================================
# 1. LOAD EXCEL DATA
# ============================================================

print("Loading Excel data...")

df = pd.read_excel(EXCEL_FILE, sheet_name=SHEET_NAME)

time = df[TIME_COLUMN].values
ax = df[X_COLUMN].values
ay = df[Y_COLUMN].values
az = df[Z_COLUMN].values


# ============================================================
# 2. CUT FIRST 3 SECONDS
# ============================================================

mask = time >= CUT_INITIAL_SECONDS

time = time[mask]
time = time - time[0]

ax = ax[mask]
ay = ay[mask]
az = az[mask]

print(f"Remaining duration: {time[-1]:.2f} s")


# ============================================================
# 3. SUBTRACT MEAN VALUE
# ============================================================

ax = ax - np.mean(ax)
ay = ay - np.mean(ay)
az = az - np.mean(az)


# ============================================================
# 4. APPLY HIGH-PASS FILTER
# ============================================================

ax_filt = highpass_filter(ax, HP_CUTOFF, FS)
ay_filt = highpass_filter(ay, HP_CUTOFF, FS)
az_filt = highpass_filter(az, HP_CUTOFF, FS)


# ============================================================
# 5. USE ONLY Z-AXIS ACCELERATION
# ============================================================

signal = az_filt

# ---- Plot filtered acceleration signal ----

plt.figure(figsize=(12, 5))

plt.plot(time, signal, linewidth=1)

plt.xlabel("Time [s]")
plt.ylabel("Acceleration")
plt.title("Filtered Z-axis Acceleration")

plt.grid(True)

plt.tight_layout()
plt.show()


# ---- Fourier spectrum ----

xf, yf = compute_fft(signal, FS)

plt.figure(figsize=(12, 5))

plt.plot(xf, yf)

# Breathing range
plt.axvspan(0.1, 0.5, alpha=0.2, label='Breathing')

# Cardiac range
plt.axvspan(0.8, 5.0, alpha=0.2, label='Cardiac')

plt.xlim(0, 10)

plt.xlabel("Frequency [Hz]")
plt.ylabel("Magnitude")

plt.title("Fourier Spectrum of Z-axis Acceleration")

plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()


# ============================================================
# 6. CALCULATE AVERAGE SIGNAL TEMPLATE
# ============================================================

peaks, properties = find_peaks(
    signal,
    distance=int(0.5 * FS),
    prominence=np.std(signal) * 0.5
)

print(f"Detected peaks: {len(peaks)}")

window_before = int(0.30 * FS)
window_after = int(0.50 * FS)

segments = []

for p in peaks:

    start = p - window_before
    stop = p + window_after

    if start >= 0 and stop < len(signal):

        seg = signal[start:stop]
        segments.append(seg)

segments = np.array(segments)

print(f"Valid heartbeat segments: {len(segments)}")

aligned_segments, avg_template = align_and_average_segments(segments)

template_time = np.arange(len(avg_template)) / FS


# ============================================================
# 7. PLOT TEMPLATE + INDIVIDUAL SIGNALS
# ============================================================

plt.figure(figsize=(10, 5))

for seg in aligned_segments:

    plt.plot(
        template_time,
        seg,
        color='grey',
        alpha=0.5,
        linewidth=1
    )

plt.plot(
    template_time,
    avg_template,
    color='red',
    linewidth=3,
    label='Average Template'
)

plt.xlabel("Time [s]")
plt.ylabel("Acceleration")

plt.title("Average Heartbeat Template")

plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()


# ============================================================
# 8. INTEGRATE ACCELERATION -> DISPLACEMENT
# ============================================================

signal_for_integration = signal - np.mean(signal)

velocity = cumulative_trapezoid(
    signal_for_integration,
    time,
    initial=0
)

velocity = velocity - np.mean(velocity)

displacement = cumulative_trapezoid(
    velocity,
    time,
    initial=0
)

# Convert m -> mm
displacement_mm = displacement * 1000

peak_to_peak_mm = (
    np.max(displacement_mm)
    - np.min(displacement_mm)
)

print()
print("===================================================")
print(f"Peak chest wall displacement: {peak_to_peak_mm:.3f} mm")
print("===================================================")

plt.figure(figsize=(12, 5))

plt.plot(time, displacement_mm, linewidth=1.5)

plt.xlabel("Time [s]")
plt.ylabel("Displacement [mm]")

plt.title("Chest Wall Displacement vs Time")

plt.grid(True)

plt.tight_layout()
plt.show()
